[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = 'CocInstall coc-lists'
