[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'
depends = ['kristijanhusak/deoplete-phpactor']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['kristijanhusak/deoplete-phpactor']

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tobyS/pdv'
